<a href="https://colab.research.google.com/github/iyngaran/zero-to-mastery-ml/blob/master/scikit_learn_workflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to Scikit-Learn (Sklearn)

This notebook demonstrates some of the most useful functions of the Scikit-Learn library

What we're going to cover: An end-to-end Scikit-Learn workflow


1. Getting the data ready
2. Choose the right estimator/algorithm for our problem
3. Fit the model/algorithm and use it to make predictions on our data
4. Evaluating a model
5. Improve the model
6. Save and load a trained model
7. Putting it all together

## An end-to-end Scikit-Learn workflow

![<caption>](https://raw.githubusercontent.com/mrdbourke/zero-to-mastery-ml/9bba622f02b07efed481a020ceab09ca55133062/images/sklearn-workflow.png)

## 1. Getting the data ready

In [ ]:
import pandas as pd
import numpy as np

heart_disease = pd.read_csv("https://raw.githubusercontent.com/iyngaran/sample-datasets/master/heart-disease.csv")
heart_disease

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

With this example, we're going to use all of the columns except the target column to predict the targert column.

In other words, using a patient's medical and demographic data to predict whether or not they have heart disease.

#### Create X (all the feature columns) and y (the target column)

In [ ]:
# Create X (all the feature columns)
X = heart_disease.drop("target", axis=1)

# Create y (the target column)
y = heart_disease["target"]

In [ ]:
X

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  
0        0   0     1  
1        0   0     2  
2        2   0     2  
3        2   0     2  
4        2   0     2  
..     ...  ..   ...  
298      1   0     3  
299      1   0     3  
300      1   2     3  
301      1   1     3  
302      1   1     2  

[303 rows x 13 columns]

In [ ]:
y

0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: target, Length: 303, dtype: int64

#### Split the data into training and test sets

In [ ]:
from sklearn.model_selection import train_test_split

# test_size=0.2 - it means 20% of data will be used for test and remaining 80% will be used for train the model
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2)

# View the data shapes
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((242, 13), (61, 13), (242,), (61,))

## 2. Choose the model/estimator

You can do this using the [Scikit-Learn machine learning map](https://scikit-learn.org/stable/tutorial/machine_learning_map/index.html)

![Scikit-Learn machine learning map](https://scikit-learn.org/stable/_static/ml_map.png)

In Scikit-Learn, machine learning models are referred to as estimators.

In this case, since we're working on a classification problem, we've chosen the RandomForestClassifier estimator which is part of the ensembles module.

In [ ]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier()

# We will keep the default hyperparameters
model.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'auto',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

## 3. Fit the model/algorithm and use it to make predictions on our data

A model will (attempt to) learn the patterns in a dataset by calling the fit() function on it and passing it the data.

In [ ]:
# Make the model to find the pattern in the training data
model.fit(X_train, y_train);

In [ ]:
# Make predictions
y_preds = model.predict(X_test)

# This will be in the same format as y_test
y_preds

array([0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1])

In [ ]:
X_test.loc[265]

age          66.0
sex           1.0
cp            0.0
trestbps    112.0
chol        212.0
fbs           0.0
restecg       0.0
thalach     132.0
exang         1.0
oldpeak       0.1
slope         2.0
ca            1.0
thal          2.0
Name: 265, dtype: float64

In [ ]:
heart_disease.loc[265]

age          66.0
sex           1.0
cp            0.0
trestbps    112.0
chol        212.0
fbs           0.0
restecg       0.0
thalach     132.0
exang         1.0
oldpeak       0.1
slope         2.0
ca            1.0
thal          2.0
target        0.0
Name: 265, dtype: float64

In [ ]:
# Make a prediction on a single sample (has to be array)
model.predict(np.array(X_test.loc[265]).reshape(1, -1))

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([0])

## 4. Evaluate the model

A trained model/estimator can be evaluated by calling the `score()` function and passing it a collection of data.

In [ ]:
# On the training set
model.score(X_train, y_train)

1.0

In [ ]:
# On the test set (unseen)
model.score(X_test, y_test)

0.8852459016393442

#### There are some more metrics that we can use rather than just accuracy

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(classification_report(y_test, y_preds))

              precision    recall  f1-score   support

           0       0.85      0.93      0.89        30
           1       0.93      0.84      0.88        31

    accuracy                           0.89        61
   macro avg       0.89      0.89      0.89        61
weighted avg       0.89      0.89      0.89        61



In [ ]:
confusion_matrix(y_test, y_preds)

array([[28,  2],
       [ 5, 26]])

In [ ]:
accuracy_score(y_test, y_preds)

0.8852459016393442

## 5. Experiment to improve (hyperparameter tuning)

A model's first evaluation metrics aren't always its last. One way to improve a models predictions is with hyperparameter tuning.

In [ ]:
# Try different numbers of estimators (n_estimators is a hyperparameter you can change)
np.random.seed(42)
for i in range(10, 100, 10):
    print(f"Trying model with {i} estimators...")
    model = RandomForestClassifier(n_estimators=i).fit(X_train, y_train)
    print(f"Model accruacy on test set: {model.score(X_test, y_test)}")
    print("")

Trying model with 10 estimators...
Model accruacy on test set: 0.8032786885245902

Trying model with 20 estimators...
Model accruacy on test set: 0.8524590163934426

Trying model with 30 estimators...
Model accruacy on test set: 0.8688524590163934

Trying model with 40 estimators...
Model accruacy on test set: 0.8852459016393442

Trying model with 50 estimators...
Model accruacy on test set: 0.8524590163934426

Trying model with 60 estimators...
Model accruacy on test set: 0.8524590163934426

Trying model with 70 estimators...
Model accruacy on test set: 0.9016393442622951

Trying model with 80 estimators...
Model accruacy on test set: 0.8852459016393442

Trying model with 90 estimators...
Model accruacy on test set: 0.9016393442622951



In [ ]:
from sklearn.model_selection import cross_val_score

# Try different numbers of estimators with cross-validation and no cross-validation
np.random.seed(42)
for i in range(10, 100, 10):
    print(f"Trying model with {i} estimators...")
    model = RandomForestClassifier(n_estimators=i).fit(X_train, y_train)
    print(f"Model accruacy on test set: {model.score(X_test, y_test)}")
    print(f"Cross-validation score: {np.mean(cross_val_score(model, X, y, cv=5)) * 100}%")
    print("")

Trying model with 10 estimators...
Model accruacy on test set: 0.8032786885245902
Cross-validation score: 78.53551912568305%

Trying model with 20 estimators...
Model accruacy on test set: 0.9016393442622951
Cross-validation score: 79.84699453551912%

Trying model with 30 estimators...
Model accruacy on test set: 0.8688524590163934
Cross-validation score: 80.50819672131148%

Trying model with 40 estimators...
Model accruacy on test set: 0.9016393442622951
Cross-validation score: 82.15300546448088%

Trying model with 50 estimators...
Model accruacy on test set: 0.8360655737704918
Cross-validation score: 81.1639344262295%

Trying model with 60 estimators...
Model accruacy on test set: 0.8688524590163934
Cross-validation score: 83.47540983606557%

Trying model with 70 estimators...
Model accruacy on test set: 0.8852459016393442
Cross-validation score: 81.83060109289617%

Trying model with 80 estimators...
Model accruacy on test set: 0.8852459016393442
Cross-validation score: 82.8142076502

## 6. Save a model for later use

A trained model can be exported and saved so it can be imported and used later. One way to save a model is using Python's `pickle` module.

In [ ]:
import pickle

# Save trained model to file - wb - Write binary
pickle.dump(model, open("random_forest_model_1.pkl", "wb"))

In [ ]:
# Load a saved model and make a prediction on a single example - rb - Read binary
loaded_model = pickle.load(open("random_forest_model_1.pkl", "rb"))
loaded_model.predict(np.array(X_test.loc[265]).reshape(1, -1))

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([0])